wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.30.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687128556.248103
    t:
      1:
      - 1
      - 9
      - 11
      - 40
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 40
      - 49
      - 55
      3:
      - 23
      - 24
      4: 3.10.0
      5: 0.15.4
      6: 4.30.0
      8:
      - 5
